---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if (.Values.dnsEntry) }} 
    # From https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.loadBalancerInternal }}"
#    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsEntry }}
    # From https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsEntry }}
    {{- end }}    
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.serviceName }}
    provider: fabric8
    version: "{{ .Values.imageTag }}"
    group: net.fhirbox.pegacorn
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: copycat
    port: {{ .Values.basePort }}
    protocol: TCP
    targetPort: 8080
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ .Values.basePort }} {{ end }}
  {{- if (.Values.wildflyAdminUser) }} 
  - name: copycat-admin
    port: {{ add 1 .Values.basePort }}
    protocol: TCP
    targetPort: 9990
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 1 .Values.basePort }} {{ end }}
  {{- end }}
  {{- if (.Values.wildflyEnableDebug) and (eq .Values.wildflyEnableDebug "Yes") }} 
  - name: copycat-debug
    port: {{ add 2 .Values.basePort }}
    protocol: TCP
    targetPort: 8787
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 2 .Values.basePort }} {{ end }}
  {{- end }}
  selector:
    app: {{ .Values.serviceName }}
    provider: fabric8
    group: net.fhirbox.pegacorn
  type: {{ .Values.serviceType | default "LoadBalancer" }}
  {{- if (.Values.loadBalancerIP) }} 
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
